networks:
  app-net:
    driver: bridge

services:
  # Nginx Proxy Reverso
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - n8n  # Apenas aguarda o container iniciar, não o healthcheck
    networks:
      - app-net

  # N8N
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    user: "1000:1000"
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://${DOMAIN}/n8n/webhook/
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      - TZ=America/Sao_Paulo
      - DB_TYPE=sqlite
      - DB_SQLITE_POOL_SIZE=3
      - N8N_RUNNERS_ENABLED=true
      - N8N_LOG_LEVEL=info
      - N8N_METRICS=false
    expose:
      - "5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5678/healthz"]
      interval: 15s
      timeout: 10s
      retries: 4
      start_period: 90s