networks:
  app-net:
    driver: bridge

services:
  # Nginx reverso manual
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - n8n
      - grafana
      - portainer
    networks:
      - app-net

  # N8N
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    environment:
      - N8N_PORT=5678
      - N8N_PATH=/n8n
      - N8N_HOST=${DOMAIN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - TZ=America/Sao_Paulo
    expose:
      - "5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - app-net

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    expose:
      - "3000"
    volumes:
      - ./grafana_data:/var/lib/grafana
    networks:
      - app-net

  # Portainer
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    expose:
      - "9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    networks:
      - app-net
