networks:
  app-net:
    driver: bridge

services:
  # Nginx Proxy Reverso
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      n8n:
        condition: service_healthy
    networks:
      - app-net

  # N8N
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    environment:
      - N8N_HOST=${DOMAIN}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://${DOMAIN}/n8n/
      - N8N_EDITOR_BASE_URL=http://${DOMAIN}/n8n/
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - TZ=America/Sao_Paulo
      - DB_TYPE=sqlite
      - DB_SQLITE_POOL_SIZE=3
      - N8N_RUNNERS_ENABLED=true
      - N8N_LOG_LEVEL=info
      - N8N_METRICS=false
    expose:
      - "5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5678/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s